package my.exception;

public class Throw1 {
    public static void main(String[] args) {
        throw new ArithmeticException("/divide by zero");
    }

}
